require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "db/**/*"
    - "vendor/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "config.ru"
    - "Gemfile"
    - "Rakefile"
  # 新しいrubocopルールはとりあえず全て有効にする
  NewCops: enable

Layout/LineLength:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 15

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/NumericLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  EnforcedStyle: brackets

Style/YodaExpression:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

RSpec/ContextWording:
  Enabled: false

RSpec/DescribedClass:
  Enabled: true
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Max: 80

RSpec/ExpectChange:
  Enabled: true
  EnforcedStyle: block

RSpec/ImplicitSubject:
  Enabled: true
  EnforcedStyle: disallow

RSpec/MultipleExpectations:
  Max: 7

RSpec/MultipleMemoizedHelpers:
  Max: 16

RSpec/NestedGroups:
  Max: 3

RSpec/NamedSubject:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false
