source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.0"

gem "puma", "6.4.2"
gem "rails", "7.1.3.1"
gem "sqlite3", "1.7.2"

group :development, :test do
  gem "debug", "1.9.1", platforms: %i[ mri mingw x64_mingw ]
  gem "rspec-rails", "6.1.1"
  gem "rubocop", "1.60.2"
  gem "rubocop-rails", "2.23.1"
  gem "rubocop-rspec", "2.22.0"
end
