source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "4.0.5"

gem "puma", "8.0.2"
gem "rails", "8.1.3"
gem "sqlite3", "2.9.5"

group :development, :test do
  gem "debug", "1.11.1", platforms: %i[ mri mingw x64_mingw ]
  gem "rspec-rails", "7.1.1"
  gem "rubocop", "1.88.0"
  gem "rubocop-rails", "2.33.4"
  gem "rubocop-rspec", "3.10.2"
end
