source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem "puma", "6.4.0"
gem "rails", "7.0.8"
gem "sqlite3", "1.6.6"

group :development, :test do
  gem "debug", "1.8.0", platforms: %i[ mri mingw x64_mingw ]
  gem "rspec-rails", "6.0.3"
  gem "rubocop", "1.56.3"
  gem "rubocop-rails", "2.21.1"
  gem "rubocop-rspec", "2.22.0"
end
