name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: bundle install
        run: bundle install
        working-directory: backend
      - name: rubocop
        run: bundle exec rubocop
        working-directory: backend
      - name: rspec
        run: bundle exec rspec
        working-directory: backend
